### ISSUE TITLE
`SIGSEGV: Illegal storage access.` when function called too often

### ISSUE THREAD

**Issue by tim-st** [yglukhov/nimpy#14]
I try to use a python function to support my test cases, but when I call the function (it should be called ~200_000 times) in a loop it will always raises the error mentioned below. It doesn't matter if the code is pure python or a linked library.
If I call it not in a loop it works as expected.

The file `icuCol.py` in the code below is the same as described [here](https://github.com/yglukhov/nimpy/issues/13).

```nim
import nimpy
let op = pyImport("operator")
let pyicu = pyImport("icuCol")
let icuCollator = pyicu.collator()

proc cmpUcaPyicu*(a, b: string): int =
  let keyA = icuCollator.getSortKey(a)
  let keyB = icuCollator.getSortKey(b)
  return op.sub(op.gt(keyA, keyB), op.gt(keyB, keyA)).to(int)
```

```
Traceback (most recent call last)
tests_uca.nim(35)        tests_uca
pyTest.nim(13)           cmpUcaPyicu
nimpy.nim(908)           nimValueToPy
nimpy.nim(499)           incRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 
```

Python version: `Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32`
Nim version:
```
Nim Compiler Version 0.18.0 [Windows: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 5ee9e86c87d831d32441db658046fc989a197ac9
active boot switches: -d:release
```

**Comment by yglukhov** [comment]
Please use newer nim. This should be fixed with https://github.com/nim-lang/Nim/pull/7885.

**Comment by tim-st** [comment]
Will try this, as soon as I can test a dev version, thanks for the quick response!

**Comment by tim-st** [comment]
With the latest nightly version the problem still exists:
```
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-06-17
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 4616b28c7b592c8204d9f77f3c1f7db2fb7186d8
active boot switches: -d:release
```

pure python (`pyuca`):
```
Traceback (most recent call last)
tests_uca.nim(36)        tests_uca
pyTest.nim(18)           cmpUcaPyuca
nimpy.nim(1149)          callMethod
nimpy.nim(1144)          callMethodAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
impure python (`pyicu`):
```
Traceback (most recent call last)
tests_uca.nim(36)        tests_uca
pyTest.nim(13)           cmpUcaPyicu
nimpy.nim(908)           nimValueToPy
nimpy.nim(499)           incRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

if the complete source codes are needed I can add them.

**Comment by yglukhov** [comment]
Ok, please provide the complete source code to reproduce the problem.

**Comment by tim-st** [comment]
The files are attached, you have to change the path to the txt file, the targeted file is `tests_uca.nim`, I tried release mode and debug mode.
I also printed the `NimVersion` and it was definetly the nightly build.
Thanks for looking at this!
[nimpyError.zip](https://github.com/yglukhov/nimpy/files/2109474/nimpyError.zip)

**Comment by tim-st** [comment]
Thanks, the first Error is fixed, when calling the impure function at `if cmpUcaPyicu(current, prevLine) != 1`
The second pure python one (that was uncommented) behaves the same like before and throws the Error mentioned already above.
It's the line `if cmpUcaPyuca(current, prevLine) != 1:`

```
NimVersion: 0.18.1
Traceback (most recent call last)
tests_uca.nim(35)        tests_uca
pyTest.nim(16)           cmpUcaPyuca
nimpy.nim(1173)          callMethod
nimpy.nim(1165)          callMethodAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by tim-st** [comment]
It works now! Thank you very much for your fixes on this issue and the other one :+1:

**Comment by yglukhov** [comment]
Yep, added that to the readme: e5668dd3c0b05a5ea98f7db77d1bd6bdbc52e535
