### ISSUE TITLE
SIGSEGV using Nim module from Django

### ISSUE THREAD

**Issue by BeneCollyridam** [yglukhov/nimpy#98]
I am using the Python web framework Django (and django-rest-framework) and want to utilize Nim's JSON library to create a response (string). I however get a segfault.
My minimal example can be found here: https://github.com/BeneCollyridam/nimpy-segfault

The Nim code looks like this:
```
import nimpy
import json
var py = pyBuiltinsModule()

proc exportToJson(questions: PyObject): string {.exportpy.} =
  echo "Created res"
  let resultJson = newJArray()
  for q in questions:
    let choices = q.choice_set.all()
    echo "Got choices ", choices
    let qjson = newJObject()
    qjson["question_text"] = %q.question_text.to(string)
    echo "Converted q to JSON ", qjson
    let choiceText = newJArray()
    for c in choices:
      add(choiceText, %c.choice_text.to(string))  # It crashes here
    qjson["choiceText"] = choiceText
    add(resultJson, qjson)
  toUgly(result, resultJson)
  return result
```
And the Python code using the Nim module looks like:
```
@api_view(["GET"])
def get_everything(request):
    qs = Question.objects.all()  # Returns a queryset that functions like a Python list
    return Response(exportToJson(qs))
```

It works well when there are less than 10 objects in my database, but when I have 20 it crashes with the following traceback:

Here is the traceback
```
Traceback (most recent call last)
nimpy.nim(884)           exportToJsonPy_wrapper
nimpy.nim(884)           pp
mylib.nim(17)            exportToJson
json.nim(306)            %
gc.nim(495)              newObjRC1
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

I hope someone can help

**Comment by yglukhov** [comment]
Wasn't it fixed by the same fix for #86? Are you using the latest nimpy?

**Comment by yglukhov** [comment]
Your steps to reproduce don't mention the last step, like `curl localhost:8000/???`.

**Comment by BeneCollyridam** [comment]
I am using:
Nim Compiler Version 0.19.2 [Linux: amd64]
And the version of nimpy is 0e08b236395aff26e6550148efaf7290fbbc74b7.
I still get the same error.

To trigger the segfault run the following commands:
- `curl http://localhost:8000/generate-questions`
- Optional: this should work without any errors
  - `curl http://localhost:8000/test`
  - `curl http://localhost:8000/nim`
- `curl http://localhost:8000/generate-questions`
- `curl http://localhost:8000/nim` - here it will segfault
I have also added the above in the repo

**Comment by yglukhov** [comment]
Ok, I can reproduce it.

**Comment by yglukhov** [comment]
It appears that the module is being invoked from multiple threads. #99 implements a better compatibility for such cases, but make sure to compile with `--threads:on`.
